### ISSUE TITLE
接收消息服务器配置URL无法调用

### ISSUE THREAD

**Issue by PM-Shawn** [mostlittlebee/chatgpt-on-wecom#9]
如图
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/34580770/224024851-90bb265a-e31c-40f6-b11f-d3d9e8050c56.png">

**Comment by Shuimo03** [comment]
需要配置域名，非常的麻烦

**Comment by jiangweiatgithub** [comment]
实在不行，就只写ip地址，立马通过（都不用验证）

**Comment by MKDJOJO** [comment]
怎么写ip地址通过呢，写IP 地址提示的也是不是一个单位，求解

**Comment by MKDJOJO** [comment]
配置回调域名有参考资料嘛？

**Comment by chrischjh** [comment]
这个现在校验非常严格，需要该域名或绑定的IP一定要是ICP备案的，而且备案的公司主体要和域名所认证的公司主体一致

**Comment by mostlittlebee** [comment]
![image](https://user-images.githubusercontent.com/66151739/226356461-ea2d22c2-2a34-423e-8684-af159d72c57b.png)

必须要设置过可信IP，最好有固定IP

**Comment by 18962211515** [comment]
忧伤，这个url比较麻烦

**Comment by duronxx** [comment]
大神在啊，域名是可信任的也是回调失败，这个地方要怎么设置，
![企业微信截图_16806989397624](https://user-images.githubusercontent.com/33643555/230085770-22b1d217-9523-4a01-9817-aa8067c5e513.png)
![企业微信截图_168069904843](https://user-images.githubusercontent.com/33643555/230085820-48c9e300-b37f-48ed-acd3-b7081064dfc5.png)

谢谢

**Comment by mostlittlebee** [comment]
![image](https://user-images.githubusercontent.com/66151739/230089612-6abce206-16ab-4acf-88e2-915237185bcb.png)
这里应该再加上 /wechat

**Comment by duronxx** [comment]
q

> ![image](https://user-images.githubusercontent.com/66151739/230089612-6abce206-16ab-4acf-88e2-915237185bcb.png)这里应该再加上 /微信
第一次配置这个，能发个图吗，麻烦了

**Comment by duronxx** [comment]
代码起动后404，这个是啥 原因啊 
![image](https://user-images.githubusercontent.com/33643555/230095998-231aa65b-4cba-4cae-bf15-aba9b9123591.png)

**Comment by duronxx** [comment]
> ![image](https://user-images.githubusercontent.com/66151739/230089612-6abce206-16ab-4acf-88e2-915237185bcb.png) 这里应该再加上 /wechat

加了测试，还是这样的，：（
![image](https://user-images.githubusercontent.com/33643555/230101150-32b02fd2-278f-40b7-b5bd-e9cd80e83a4b.png)

**Comment by duronxx** [comment]
回调成功，但问消息，不能回复，报错如下，大神能指点下啊：[INFO][2023-04-06 09:09:16][chat_gpt_bot.py:19] - [OPEN_AI] query=你在工作吗
[2023-04-06 09:09:16,960] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 25, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 87, in handle
    self.client.message.send_text(self.AppId,msg.source,reply)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 142, in _handle_result
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1680743356365203768504018], from ip: 139.227.20.128, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
183.47.98.227 - - [06/Apr/2023 09:09:16] "POST /wechat?msg_signature=59e7c39f12288519a1c3f994f179a1b79f2122ff&timestamp=1680743351&nonce=1680365568 HTTP/1.1" 500 -
[INFO][2023-04-06 09:09:21][chat_gpt_bot.py:19] - [OPEN_AI] query=你在工作吗
[2023-04-06 09:09:22,008] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 25, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 87, in handle
    self.client.message.send_text(self.AppId,msg.source,reply)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 142, in _handle_result
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1680743361307413153807921], from ip: 139.227.20.128, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
106.55.201.217 - - [06/Apr/2023 09:09:22] "POST /wechat?msg_signature=59e7c39f12288519a1c3f994f179a1b79f2122ff&timestamp=1680743351&nonce=1680365568 HTTP/1.1" 500 -
[INFO][2023-04-06 09:09:26][chat_gpt_bot.py:19] - [OPEN_AI] query=你在工作吗
[2023-04-06 09:09:27,285] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 25, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 87, in handle
    self.client.message.send_text(self.AppId,msg.source,reply)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 142, in _handle_result
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1680743367612131734211782], from ip: 139.227.20.128, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
175.27.32.31 - - [06/Apr/2023 09:09:27] "POST /wechat?msg_signature=59e7c39f12288519a1c3f994f179a1b79f2122ff&timestamp=1680743351&nonce=1680365568 HTTP/1.1" 500 -
[INFO][2023-04-06 09:09:31][chat_gpt_bot.py:19] - [OPEN_AI] query=你在工作吗
[2023-04-06 09:09:32,116] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 25, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 87, in handle
    self.client.message.send_text(self.AppId,msg.source,reply)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 142, in _handle_result
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1680743372303760129892390], from ip: 139.227.20.128, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
183.47.98.168 - - [06/Apr/2023 09:09:32] "POST /wechat?msg_signature=59e7c39f12288519a1c3f994f179a1b79f2122ff&timestamp=1680743351&nonce=1680365568 HTTP/1.1" 500 -
[2023-04-06 09:09:32,168] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 25, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 87, in handle
    self.client.message.send_text(self.AppId,msg.source,reply)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 142, in _handle_result
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1680743372339601936772701], from ip: 139.227.20.128, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
43.137.215.241 - - [06/Apr/2023 09:09:32] "POST /wechat?msg_signature=59e7c39f12288519a1c3f994f179a1b79f2122ff&timestamp=1680743351&nonce=1680365568 HTTP/1.1" 500 -
[INFO][2023-04-06 09:09:32][chat_gpt_bot.py:19] - [OPEN_AI] query=你在工作吗
[2023-04-06 09:09:32,655] ERROR in app: Exception on /wechat [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 25, in handler_msg
    return WechatEnterpriseChannel().handle()
  File "/data/wx/chatgpt-on-wecom-main/channel/wechatcom/wechatenterprise_channel.py", line 87, in handle
    self.client.message.send_text(self.AppId,msg.source,reply)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 62, in send_text
    return self.send(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/enterprise/client/api/message.py", line 58, in send
    return self._post('message/send', data=data)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/api/base.py", line 19, in _post
    return self._client.post(url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 182, in post
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 142, in _handle_result
    return self._request(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 101, in _request
    return self._handle_result(
  File "/usr/local/python3/lib/python3.8/site-packages/wechatpy/client/base.py", line 158, in _handle_result
    raise WeChatClientException(
wechatpy.exceptions.WeChatClientException: Error code: 60020, message: not allow to access from your ip, hint: [1680743372365202008231868], from ip: 139.227.20.128, more info at https://open.work.weixin.qq.com/devtool/query?e=60020
183.47.98.227 - - [06/Apr/2023 09:09:32] "POST /wechat?msg_signature=59e7c39f12288519a1c3f994f179a1b79f2122ff&timestamp=1680743351&nonce=1680365568 HTTP/1.1" 500 -

**Comment by duronxx** [comment]
![image](https://user-images.githubusercontent.com/33643555/230260767-dda2a7ac-8182-4d71-a758-7b473c8c28f8.png)
终于运行起来，但收不到回复 ，用官方的api接口，这个是被封了吧，这个能成自己的代理 接口啊》？

**Comment by Rogarliu** [comment]
![image](https://user-images.githubusercontent.com/53483845/231505147-9fe1a615-9178-4746-8c5f-4295798fc55a.png)
我也遇到了同样的问题，楼主解决了吗？
